Compiler flag changes and post link commands added

diff --git a/xbx-2.0.1/platforms/msp430fg4618_4mhz/postlink b/xbx-2.0.1/platforms/msp430fg4618_4mhz/postlink
--- a/xbx-2.0.1/platforms/msp430fg4618_4mhz/postlink
+++ b/xbx-2.0.1/platforms/msp430fg4618_4mhz/postlink
@@ -1,3 +1,28 @@
 #!/bin/bash
 
-#empty
+maxSize=$1
+if [ -z "$maxSize" ]
+then
+  exit -1
+fi
+
+if [ -e xbdprog.bin ]
+then
+  totalsize=`msp430-size xbdprog.bin | tail -n 1 | awk '{print $4}'`
+  if [ $totalsize -ge $maxSize ]
+  then
+    echo "Postlink: Binary too large ($totalsize bytes)" >&2
+    rm xbdprog.bin
+    exit -1
+  fi
+fi
+
+if [ -e xbdprog.bin ]
+then
+  HEX_FLASH_FLAGS="-R .eeprom -R .fuse -R .lock -R .signature"
+  msp430-objcopy -O ihex ${HEX_FLASH_FLAGS}  xbdprog.bin xbdprog.hex
+else
+  echo "Postlink: Objcopy failed" >&2
+  exit -1
+fi
+
